_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 60
DATASETS:
  TRAIN: ('coco_trainval_base',)
  TEST: ('coco_test_base',)
SOLVER:
  # Values determined by taking the original values, dividing the LR by 4 and multiyplying iterations by 4
  # This follows the learning rate rule.
  # BASE_LR: 0.005
  # IMS_PER_BATCH: 4
  # STEPS: (240000, 320000)
  # MAX_ITER: 360000
  BASE_LR: 0.01
  IMS_PER_BATCH: 8
  STEPS: (160000, 200000)
  MAX_ITER: 220000
# Original values:
# --------------------
# IMS_PER_BATCH: 16
# BASE_LR: 0.02
# STEPS: (60000, 80000)
# MAX_ITER: 90000
# --------------------
# From few-shot-object-detection paper:
#  IMS_PER_BATCH: 16
#  STEPS: (85000, 100000)
#  MAX_ITER: 110000
# --------------------
OUTPUT_DIR: "checkpoints/BaseModel_MRCNN_R_101_FPN"
